-- MySQL Script generated by MySQL Workbench
-- Mon Jul 16 18:56:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema secretsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema secretsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secretsdb` DEFAULT CHARACTER SET utf8 ;
USE `secretsdb` ;

-- -----------------------------------------------------
-- Table `secretsdb`.`Ninjas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretsdb`.`Ninjas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(255) NULL,
  `Created_At` DATETIME NULL,
  `Updated_At` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretsdb`.`Secrets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretsdb`.`Secrets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(45) NULL,
  `Created_At` DATETIME NULL,
  `Updated_At` VARCHAR(45) NULL,
  `CreatorId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Secrets_Ninjas_idx` (`CreatorId` ASC),
  CONSTRAINT `fk_Secrets_Ninjas`
    FOREIGN KEY (`CreatorId`)
    REFERENCES `secretsdb`.`Ninjas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretsdb`.`Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretsdb`.`Likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Created_At` DATETIME NULL,
  `Updated_At` DATETIME NULL,
  `PromoterId` INT NOT NULL,
  `LikedId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Likes_Ninjas1_idx` (`PromoterId` ASC),
  INDEX `fk_Likes_Secrets1_idx` (`LikedId` ASC),
  CONSTRAINT `fk_Likes_Ninjas1`
    FOREIGN KEY (`PromoterId`)
    REFERENCES `secretsdb`.`Ninjas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likes_Secrets1`
    FOREIGN KEY (`LikedId`)
    REFERENCES `secretsdb`.`Secrets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
